### ISSUE TITLE
When will I be able to see an solution of example?

### ISSUE THREAD

**Issue by oortclwd** [mastering-python/exercises#1]
Hi. I am enjoying your mastering python book. 
When will I be able to see an solution of example?

**Comment by wolph** [comment]
I've been working on it but it's taking quite a bit of time and I'm very limited in time right now. If you have any specific exercises that you want a solution for, please let me know. That should be much faster to arrange :)

**Comment by oortclwd** [comment]
Can I get the solution from Ch.13(asyncio) and Ch.14(multiprocessing) first? Thank you for answer.

**Comment by wolph** [comment]
I've added some example solutions for those chapters :)

You are welcome (and encouraged) to fork and add your own version with improvements.
